### ISSUE TITLE
game thumbnails stretch on md-lg screens

### ISSUE THREAD

**Issue by jajord** [armac7/golf-lab#11]
on medium-large screens, the image for each game streches/compresses horizontally in an unpleasant way
example below at screen width around 800px: 
![image](https://github.com/armac7/golf-lab/assets/143463845/b2128b80-dcdc-474c-9e7c-84ca9451e3c0)

**Comment by armac7** [comment]
Intended bug for "old crappy site" aesthetic, but if we don't like the "joke" (if you can call it that), we can change it!
